\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex

@node Top
@c @top Maze
@chapter Maze
Программу Maze позволяюет генерировать и отрисовывать идеальные лабиринты и пещеры:

@itemize
@item
Программа разработана на языке C++ стандарта C++17
@item
Код программы находиться в папке src
@item
Сборка программы настроена с помощью Makefile со стандартным набором целей для GNU-программ: all, install, uninstall, clean, dvi, dist, tests.
@item
В программе реализован графический пользовательский интерфейс на базе Qt.
@item
В программе предусмотрена кнопка для загрузки лабиринта из файла.
@end itemize

Максимальный размер лабиринта - 50х50
Загруженный лабиринт отрисовывается на экране в поле размером 500 x 500 пикселей
Толщина "стены" - 2 пикселя
Размер самих ячеек лабиринта вычисляется таким образом, чтобы лабиринт занимает всё отведенное под него поле

@itemize
@item
Лабиринт генерируется согласно алгоритму Эллера
@item
Сгенерированный лабиринт не имеет изолированных областей и петель
@item
Обеспечено полное покрытие unit-тестами модуля генерации идеального лабиринта
@item
Пользователем вводится только размерность лабиринта: количество строк и столбцов
@item
В программе предусмотрена кнопка для сохранения в файл
@end itemize

Добавлена возможность показать решение любого лабиринта, который сейчас изображен на экране:
@itemize
@item
Пользователем задаются начальная и конечная точки
@item
Маршрут, являющийся решением, отображается линией толщиной 2 пикселя, проходящей через середины всех ячеек лабиринта, через которые пролегает решение
@item
Цвет линии решения отличается от цветов стен и поля
@item
Обеспечено полное покрытие unit-тестами модуля решения лабиринта
@end itemize

@chapter Cave
Добавлена генерацию пещер с использованием клеточного автомата:

@itemize
@item
Пользователем выбирается файл, в котором описана пещера по описанному выше формату
@item
Максимальный размер пещеры - 50 х 50
@item
Загруженная пещера отрисована на экране в поле размером 500 x 500 пикселей
@item
Пользователем задаются пределы "рождения" и "смерти" клетки, а также шанс на начальную инициализацию клетки
@item
Пределы "рождения" и "смерти" могут иметь значения от 0 до 7
@item
Предусмотрен пошаговый режим отрисовки результатов работы алгоритма в двух вариантах:

@itemize
@item
По нажатию на кнопку следующего шага отрисовывается очередная итерация работы алгоритма
@item
По нажатию на кнопку автоматической работы запускается отрисовка итераций работы алгоритма с частотой 1 шаг в N миллисекунд, где число миллисекунд N задаётся через специальное поле в пользовательском интерфейсе
@end itemize

@item
Размер клеток в пикселях вычисляется таким образом, чтобы пещера занимала всё отведенное под него поле
@item
Обеспечено полное покрытие unit-тестами модуля генерации пещер
@end itemize

@bye
